SCENE = { {track = 1, text = [[test test test]]},
    {track = 1, behavior = "setscene", setscene = {line = 6}},
    {track = 1, text = [[this text is auto]], behavior = "auto"},
    {track = 1, text = [[BOO]], style = {red = true}},
    {track = 1, behavior = "setscene", setscene = {line = 9}},
    {track = 1, text = [[this is a choice]], behavior = "choice",
    choices = {
        {name = "right", location = "right", gototrack = 1},
        {name = "left", location = "left", gototrack = 1},
        {name = "top", location = "top", gototrack = 1},
        {name = "bottom", location = "bottom", gototrack = 1},
        {name = "center", location = "center", gototrack = 1},
        {name = "top left", location = "topleft", gototrack = 1},
        {name = "top right", location = "topright", gototrack = 1},
        {name = "bottom right", location = "bottomright", gototrack = 1},
        {name = "bottom left", location = "bottomleft", gototrack = 1},
    }},
    {track = 1, text = [[yes]], style = {"blue"}},
    {track = 1, behavior = "setscene", setscene = {line = 3}},
    {track = 1, text = [[BOO2]], style = {"red"}},
}